name: React CI/CD

on:
  push:
    branches:
      - main # Run this workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use a Node.js version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional, remove if you don't have tests)
      - name: Run tests
        run: npm test -- --watchAll=false

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.1.1
        with:
          publish-dir: ./build # Directory with the output of the build
          production-deploy: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
